#!/bin/sh

echo ""
echo "===== Centegix Network rebuild ====="

# Step 0: Hostname and time
HOST=$(uname -a)
[ -z "$HOST" ] && HOST="uname -a"
echo "Running on $HOST at $(date)"

# Step 1: Shutdown Zigbee network
echo ""
echo "1. Shutdown Zigbee network:
mycdfunction() {
  cd /home/centegix/gateway || exit 1
}
echo ""
echo "===Done==="
